export interface ProdutoMock {
  id: string;
  productId?: string;
  supplierId?: string;
  nome: string;
  fornecedor: string;
  categoria: string;
  categoriaSlug: string;
  cidade: string;
  estado: string;
  precoMin: number;
  precoMax: number;
  unidade: string;
  pedidoMinimo: number;
  prazoEntrega: number; // dias
  descricao: string;
  tags: string[];
  tipo: "fabrica" | "atacado" | "varejo" | "importacao";
}

export const CATEGORIAS = [
  { slug: "embalagens",             nome: "Embalagens" },
  { slug: "alimentos-bebidas",      nome: "Alimentos e Bebidas" },
  { slug: "materiais-construcao",   nome: "Materiais de Construção" },
  { slug: "textil-confeccao",       nome: "Têxtil e Confecção" },
  { slug: "autopecas",              nome: "Autopeças" },
  { slug: "industria-manufatura",   nome: "Indústria e Manufatura" },
  { slug: "tecnologia",             nome: "Tecnologia" },
  { slug: "agronegocio",            nome: "Agronegócio" },
  { slug: "limpeza-higiene",        nome: "Limpeza e Higiene" },
];

export const PRODUTOS_MOCK: ProdutoMock[] = [
  // ── Embalagens (22) ──────────────────────────────────────────────────────
  { id:"e01", nome:"Caixa de papelão ondulado duplo", fornecedor:"EmbalaBox Ind. e Com.", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"Americana", estado:"SP", precoMin:0.85, precoMax:3.20, unidade:"unid", pedidoMinimo:500, prazoEntrega:5, descricao:"Caixa de papelão duplo wall para e-commerce e logística. Personalização com logo disponível.", tags:["papelão","caixa","e-commerce","logística"], tipo:"fabrica" },
  { id:"e02", nome:"Sacola kraft 100% reciclável", fornecedor:"EcoPack Brasil", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"São Paulo", estado:"SP", precoMin:0.45, precoMax:1.80, unidade:"unid", pedidoMinimo:1000, prazoEntrega:7, descricao:"Sacola de papel kraft com alça torcida, ideal para varejo e feiras. Disponível em 4 tamanhos.", tags:["kraft","reciclável","sustentável","varejo"], tipo:"atacado" },
  { id:"e03", nome:"Pote plástico PP transparente 500ml", fornecedor:"Plastiform Embalagens", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"Joinville", estado:"SC", precoMin:0.60, precoMax:2.10, unidade:"unid", pedidoMinimo:2000, prazoEntrega:8, descricao:"Pote PP transparente com tampa rosca, aprovado para contato alimentar. Ideal para indústria de alimentos.", tags:["plástico","alimentar","pote","transparente"], tipo:"fabrica" },
  { id:"e04", nome:"Fita adesiva BOPP impressa", fornecedor:"TapeMax Ind.", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"Guarulhos", estado:"SP", precoMin:1.20, precoMax:4.50, unidade:"rolo", pedidoMinimo:200, prazoEntrega:4, descricao:"Fita adesiva BOPP 45mm x 100m, impressão com logo em até 2 cores. Colagem forte para papelão.", tags:["fita","adesiva","BOPP","personalizada"], tipo:"fabrica" },
  { id:"e05", nome:"Embalagem a vácuo PA/PE 20x30cm", fornecedor:"VacPack Embalagens", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"Bauru", estado:"SP", precoMin:0.22, precoMax:0.90, unidade:"unid", pedidoMinimo:5000, prazoEntrega:6, descricao:"Saco a vácuo PA/PE transparente para alimentos. Alta barreira, aprovado ANVISA.", tags:["vácuo","alimentar","PA/PE","barreira"], tipo:"fabrica" },
  { id:"e06", nome:"Caixinha cartonada para presente", fornecedor:"Luxbox Embalagens", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"São Paulo", estado:"SP", precoMin:1.50, precoMax:6.00, unidade:"unid", pedidoMinimo:300, prazoEntrega:10, descricao:"Caixinha cartonada com janela PVC, ideal para perfumaria, cosméticos e presentes corporativos.", tags:["presente","cartonada","cosméticos","premium"], tipo:"atacado" },
  { id:"e07", nome:"Bandeja de isopor EPS nº 8", fornecedor:"IsoForm Brasil", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"Campinas", estado:"SP", precoMin:0.08, precoMax:0.30, unidade:"unid", pedidoMinimo:10000, prazoEntrega:3, descricao:"Bandeja EPS nº 8 para açougue e peixaria. Alta absorção, ideal para proteína animal.", tags:["isopor","EPS","açougue","proteína"], tipo:"fabrica" },
  { id:"e08", nome:"Garrafa PET 500ml transparente", fornecedor:"PETBras Embalagens", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"Santo André", estado:"SP", precoMin:0.35, precoMax:1.10, unidade:"unid", pedidoMinimo:3000, prazoEntrega:7, descricao:"Garrafa PET 500ml com bocal 28mm, ideal para bebidas, molhos e laticínios.", tags:["PET","garrafa","bebida","laticínio"], tipo:"fabrica" },
  { id:"e09", nome:"Bobina stretch manual 25cm x 300m", fornecedor:"StretchPak Ind.", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"Diadema", estado:"SP", precoMin:18.00, precoMax:35.00, unidade:"rolo", pedidoMinimo:50, prazoEntrega:2, descricao:"Filme stretch manual 25cm x 300m, espessura 20µm. Ideal para paletização e segurança de cargas.", tags:["stretch","paletização","bobina","logística"], tipo:"atacado" },
  { id:"e10", nome:"Envelope plástico segurança 19x25cm", fornecedor:"SafeEnvelope Brasil", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"São Paulo", estado:"SP", precoMin:0.55, precoMax:2.00, unidade:"unid", pedidoMinimo:500, prazoEntrega:3, descricao:"Envelope plástico com fecho lacre para e-commerce. Inviolável, disponível em 5 tamanhos.", tags:["envelope","e-commerce","segurança","lacre"], tipo:"atacado" },
  { id:"e11", nome:"Caixa rígida papelão microondulado", fornecedor:"RigidBox Emb.", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"Ribeirão Preto", estado:"SP", precoMin:2.00, precoMax:8.50, unidade:"unid", pedidoMinimo:200, prazoEntrega:12, descricao:"Caixa rígida microondulado com aba, ideal para eletrônicos e produtos de alto valor.", tags:["rígida","microondulado","eletrônicos","premium"], tipo:"fabrica" },
  { id:"e12", nome:"Lacre plástico para frasco 28mm", fornecedor:"CapSeal Ind.", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"Hortolândia", estado:"SP", precoMin:0.03, precoMax:0.12, unidade:"unid", pedidoMinimo:20000, prazoEntrega:5, descricao:"Lacre termoencolhível PVC 28mm para frascos, garante inviolabilidade. Aprovado ANVISA.", tags:["lacre","PVC","termoencolhível","frasco"], tipo:"fabrica" },
  { id:"e13", nome:"Bag de ráfia PP 60x100cm", fornecedor:"RáfiaBag Brasil", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"Americana", estado:"SP", precoMin:1.80, precoMax:5.50, unidade:"unid", pedidoMinimo:500, prazoEntrega:8, descricao:"Bag de ráfia PP laminado 60x100cm, capacidade 50kg. Para grãos, fertilizantes e construção.", tags:["ráfia","grãos","fertilizante","big bag"], tipo:"fabrica" },
  { id:"e14", nome:"Frasco HDPE branco 250ml", fornecedor:"FrascoTech", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"São Bernardo do Campo", estado:"SP", precoMin:0.80, precoMax:2.80, unidade:"unid", pedidoMinimo:1000, prazoEntrega:7, descricao:"Frasco HDPE branco 250ml com tampa flip top, aprovado para cosméticos e produtos de limpeza.", tags:["HDPE","frasco","cosméticos","limpeza"], tipo:"fabrica" },
  { id:"e15", nome:"Papel seda 50x70cm branco", fornecedor:"SedaBr Papéis", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"São Paulo", estado:"SP", precoMin:0.18, precoMax:0.55, unidade:"folha", pedidoMinimo:2000, prazoEntrega:4, descricao:"Papel seda 17g branco 50x70cm para embrulho de roupas, sapatos e presentes.", tags:["seda","papel","embrulho","roupa"], tipo:"atacado" },
  { id:"e16", nome:"Caixa pizza dupla 35cm", fornecedor:"PizzaBox Emb.", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"Osasco", estado:"SP", precoMin:0.70, precoMax:2.20, unidade:"unid", pedidoMinimo:500, prazoEntrega:5, descricao:"Caixa para pizza 35cm dupla com logo da pizzaria impresso. Personalização em até 4 cores.", tags:["pizza","caixa","alimentar","personalizada"], tipo:"fabrica" },
  { id:"e17", nome:"Filme PVC esticável 30cm x 400m", fornecedor:"ClearPack Ind.", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"Mauá", estado:"SP", precoMin:25.00, precoMax:55.00, unidade:"rolo", pedidoMinimo:20, prazoEntrega:3, descricao:"Filme PVC 30cm x 400m para açougue e hortifrúti. Alta transparência, aderência forte.", tags:["PVC","filme","açougue","hortifrúti"], tipo:"fabrica" },
  { id:"e18", nome:"Saco multiwall papel 25kg", fornecedor:"PaperSack Brasil", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"Curitiba", estado:"PR", precoMin:1.20, precoMax:4.00, unidade:"unid", pedidoMinimo:1000, prazoEntrega:10, descricao:"Saco multiwall 3 folhas 25kg para cimento, farinha e rações. Resistente a umidade.", tags:["multiwall","cimento","farinha","ração"], tipo:"fabrica" },
  { id:"e19", nome:"Etiqueta adesiva 10x15cm BOPP fosco", fornecedor:"LabelPrint Gráfica", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"São Paulo", estado:"SP", precoMin:0.12, precoMax:0.45, unidade:"unid", pedidoMinimo:2000, prazoEntrega:6, descricao:"Etiqueta adesiva BOPP fosco 10x15cm, impressão digital 4 cores. Resistente à água e óleo.", tags:["etiqueta","BOPP","adesiva","impressão"], tipo:"fabrica" },
  { id:"e20", nome:"Caixa corrugada exportação duplo muro", fornecedor:"ExportBox Ind.", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"São Paulo", estado:"SP", precoMin:3.50, precoMax:12.00, unidade:"unid", pedidoMinimo:200, prazoEntrega:8, descricao:"Caixa corrugada duplo muro para exportação. Resistência Edge Crush Test mínima de 32 ECT.", tags:["exportação","corrugada","duplo muro","ECT"], tipo:"fabrica" },
  { id:"e21", nome:"Blister PVC cristal termoformado", fornecedor:"BlistForm Emb.", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"ABC Paulista", estado:"SP", precoMin:0.30, precoMax:1.20, unidade:"unid", pedidoMinimo:3000, prazoEntrega:15, descricao:"Blister PVC cristal termoformado sob medida para brinquedos, ferramentas e cosméticos.", tags:["blister","PVC","termoformado","personalizado"], tipo:"fabrica" },
  { id:"e22", nome:"Pallete plástico 1,20x1,00m", fornecedor:"PalletBr", categoria:"Embalagens", categoriaSlug:"embalagens", cidade:"Guarulhos", estado:"SP", precoMin:85.00, precoMax:180.00, unidade:"unid", pedidoMinimo:10, prazoEntrega:5, descricao:"Pallete plástico virgem 1,20x1,00m cap. 1200kg estático. Lavável e reutilizável.", tags:["pallete","plástico","logística","armazém"], tipo:"atacado" },

  // ── Alimentos e Bebidas (14) ─────────────────────────────────────────────
  { id:"a01", nome:"Açúcar cristal premium ICUMSA 150", fornecedor:"Sucroeste Ind.", categoria:"Alimentos e Bebidas", categoriaSlug:"alimentos-bebidas", cidade:"Araçatuba", estado:"SP", precoMin:2.80, precoMax:4.20, unidade:"kg", pedidoMinimo:1000, prazoEntrega:7, descricao:"Açúcar cristal premium ICUMSA 150 ensacado 50kg. Laudo de qualidade incluso. Origem Brasil.", tags:["açúcar","ICUMSA","cristal","premium"], tipo:"fabrica" },
  { id:"a02", nome:"Whey Protein concentrado 80% granel", fornecedor:"NutriWhey Brasil", categoria:"Alimentos e Bebidas", categoriaSlug:"alimentos-bebidas", cidade:"Limeira", estado:"SP", precoMin:18.00, precoMax:28.00, unidade:"kg", pedidoMinimo:25, prazoEntrega:5, descricao:"Whey concentrado 80% proteína granel, origem USA/NZ. Laudo microbiológico e nutricional.", tags:["whey","proteína","suplemento","granel"], tipo:"importacao" },
  { id:"a03", nome:"Café torrado e moído blend especial", fornecedor:"Cafeteira do Vale", categoria:"Alimentos e Bebidas", categoriaSlug:"alimentos-bebidas", cidade:"Machado", estado:"MG", precoMin:22.00, precoMax:38.00, unidade:"kg", pedidoMinimo:20, prazoEntrega:3, descricao:"Blend especial arábica/robusta, torrado e moído na planta. SCA 80+, ideal para cafeterias.", tags:["café","torrado","blend","arábica"], tipo:"fabrica" },
  { id:"a04", nome:"Polpa de fruta congelada mix tropical", fornecedor:"TropicalFrut", categoria:"Alimentos e Bebidas", categoriaSlug:"alimentos-bebidas", cidade:"Fortaleza", estado:"CE", precoMin:8.00, precoMax:16.00, unidade:"kg", pedidoMinimo:50, prazoEntrega:10, descricao:"Mix de polpas congeladas: maracujá, caju, acerola e manga. Embalagem de 1kg cada. Sem conservantes.", tags:["polpa","congelado","tropical","fruta"], tipo:"fabrica" },
  { id:"a05", nome:"Farinha de trigo tipo 1 especial 50kg", fornecedor:"Moagem São Bento", categoria:"Alimentos e Bebidas", categoriaSlug:"alimentos-bebidas", cidade:"Mogi Mirim", estado:"SP", precoMin:1.90, precoMax:2.80, unidade:"kg", pedidoMinimo:500, prazoEntrega:5, descricao:"Farinha de trigo tipo 1 saco 50kg. W180-200, ideal para pães, biscoitos e massas.", tags:["farinha","trigo","padaria","massa"], tipo:"fabrica" },
  { id:"a06", nome:"Óleo de soja refinado galão 5L", fornecedor:"Oleagro Ind.", categoria:"Alimentos e Bebidas", categoriaSlug:"alimentos-bebidas", cidade:"Rondonópolis", estado:"MT", precoMin:6.50, precoMax:9.80, unidade:"unid", pedidoMinimo:200, prazoEntrega:8, descricao:"Óleo de soja refinado 5L, galão lacrado. Sem transgênicos. Azeite de origem certificada.", tags:["óleo","soja","refinado","cozinha"], tipo:"fabrica" },
  { id:"a07", nome:"Erva-mate chimarrão premium", fornecedor:"Gaúcha Erva Mate", categoria:"Alimentos e Bebidas", categoriaSlug:"alimentos-bebidas", cidade:"Erechim", estado:"RS", precoMin:12.00, precoMax:22.00, unidade:"kg", pedidoMinimo:50, prazoEntrega:6, descricao:"Erva-mate chimarrão colheita selecionada, curado em câmara fria. Finura média-grossa.", tags:["erva-mate","chimarrão","gaúcho","granel"], tipo:"fabrica" },
  { id:"a08", nome:"Castanha-do-pará extra graúda granel", fornecedor:"AmazôniaNuts", categoria:"Alimentos e Bebidas", categoriaSlug:"alimentos-bebidas", cidade:"Belém", estado:"PA", precoMin:25.00, precoMax:42.00, unidade:"kg", pedidoMinimo:20, prazoEntrega:12, descricao:"Castanha-do-pará extra graúda, rastreável de extrativistas do Pará. Laudo aflatoxina OK.", tags:["castanha","pará","granel","extrativismo"], tipo:"fabrica" },
  { id:"a09", nome:"Mel de abelha puro granel 300kg", fornecedor:"ApiMel do Nordeste", categoria:"Alimentos e Bebidas", categoriaSlug:"alimentos-bebidas", cidade:"Petrolina", estado:"PE", precoMin:18.00, precoMax:30.00, unidade:"kg", pedidoMinimo:20, prazoEntrega:8, descricao:"Mel de abelha puro granel unifloral (angico), laudo de umidade e HMF. SIF.", tags:["mel","abelha","granel","natural"], tipo:"fabrica" },
  { id:"a10", nome:"Tempero alho granulado a granel", fornecedor:"Temperos Goiás", categoria:"Alimentos e Bebidas", categoriaSlug:"alimentos-bebidas", cidade:"Cristalina", estado:"GO", precoMin:14.00, precoMax:26.00, unidade:"kg", pedidoMinimo:25, prazoEntrega:5, descricao:"Alho granulado 0,5-1,5mm granel, desidratado em câmara. Umidade < 6%. SIF/MAPA.", tags:["alho","granulado","tempero","granel"], tipo:"fabrica" },
  { id:"a11", nome:"Biscoito cream cracker granel atacado", fornecedor:"Biscoitos Nação", categoria:"Alimentos e Bebidas", categoriaSlug:"alimentos-bebidas", cidade:"Natal", estado:"RN", precoMin:7.50, precoMax:12.00, unidade:"kg", pedidoMinimo:50, prazoEntrega:7, descricao:"Biscoito cream cracker granel caixa 10kg. Produção própria, prazo de validade 6 meses.", tags:["biscoito","cream cracker","granel","atacado"], tipo:"atacado" },
  { id:"a12", nome:"Extrato de tomate concentrado 2x 5kg", fornecedor:"TomateMax Ind.", categoria:"Alimentos e Bebidas", categoriaSlug:"alimentos-bebidas", cidade:"Goiânia", estado:"GO", precoMin:22.00, precoMax:35.00, unidade:"unid", pedidoMinimo:50, prazoEntrega:6, descricao:"Extrato de tomate concentrado duplo 28-30° brix, lata 5kg. Tomate nacional processado na hora.", tags:["extrato","tomate","concentrado","brix"], tipo:"fabrica" },
  { id:"a13", nome:"Cerveja artesanal IPA long neck 355ml", fornecedor:"Brew Paulista", categoria:"Alimentos e Bebidas", categoriaSlug:"alimentos-bebidas", cidade:"São Paulo", estado:"SP", precoMin:5.50, precoMax:8.00, unidade:"unid", pedidoMinimo:120, prazoEntrega:5, descricao:"IPA artesanal 6% alc., long neck 355ml em caixas de 12. Lúpulo Citra e Centennial.", tags:["cerveja","artesanal","IPA","craft"], tipo:"fabrica" },
  { id:"a14", nome:"Água mineral natural sem gás 20L", fornecedor:"Fonte Serrana Água", categoria:"Alimentos e Bebidas", categoriaSlug:"alimentos-bebidas", cidade:"Serra Negra", estado:"SP", precoMin:12.00, precoMax:18.00, unidade:"unid", pedidoMinimo:50, prazoEntrega:2, descricao:"Água mineral natural sem gás, galão 20L. Entrega com troca de vasilhame.", tags:["água","mineral","galão","sem gás"], tipo:"fabrica" },

  // ── Materiais de Construção (13) ─────────────────────────────────────────
  { id:"c01", nome:"Cimento CP II-F-32 saco 50kg", fornecedor:"CimePar Ind.", categoria:"Materiais de Construção", categoriaSlug:"materiais-construcao", cidade:"Votorantim", estado:"SP", precoMin:28.00, precoMax:38.00, unidade:"saco", pedidoMinimo:100, prazoEntrega:3, descricao:"Cimento CP II-F-32 ABNT NBR 11578, saco 50kg. Excelente trabalhabilidade e resistência.", tags:["cimento","CP2","construção","estrutural"], tipo:"fabrica" },
  { id:"c02", nome:"Tijolo cerâmico furado 9 furos 9x14x19", fornecedor:"Cerâmica Vale Verde", categoria:"Materiais de Construção", categoriaSlug:"materiais-construcao", cidade:"Santa Gertrudes", estado:"SP", precoMin:0.65, precoMax:1.20, unidade:"unid", pedidoMinimo:5000, prazoEntrega:7, descricao:"Tijolo cerâmico furado 9 furos, queima de qualidade. ABNT NBR 15270. Frete negociável.", tags:["tijolo","cerâmico","alvenaria","furado"], tipo:"fabrica" },
  { id:"c03", nome:"Vergalhão CA-50 10mm barra 12m", fornecedor:"AçoVale Distribuidora", categoria:"Materiais de Construção", categoriaSlug:"materiais-construcao", cidade:"Belo Horizonte", estado:"MG", precoMin:65.00, precoMax:95.00, unidade:"barra", pedidoMinimo:50, prazoEntrega:5, descricao:"Vergalhão CA-50 10mm barra 12m. Norma ABNT NBR 7480. Origem Gerdau/ArcelorMittal.", tags:["vergalhão","CA50","aço","estrutural"], tipo:"atacado" },
  { id:"c04", nome:"Tinta acrílica premium 18L branca", fornecedor:"CorpBras Tintas", categoria:"Materiais de Construção", categoriaSlug:"materiais-construcao", cidade:"Jundiaí", estado:"SP", precoMin:185.00, precoMax:280.00, unidade:"balde", pedidoMinimo:20, prazoEntrega:4, descricao:"Tinta acrílica premium 18L branco neve. Rendimento 250m²/demão, cobertura total em 2x.", tags:["tinta","acrílica","premium","construção"], tipo:"fabrica" },
  { id:"c05", nome:"Piso porcelanato polido 60x60 1ª linha", fornecedor:"CerâmicaTech Brasil", categoria:"Materiais de Construção", categoriaSlug:"materiais-construcao", cidade:"Santa Gertrudes", estado:"SP", precoMin:35.00, precoMax:65.00, unidade:"m²", pedidoMinimo:50, prazoEntrega:8, descricao:"Porcelanato polido 60x60 1ª linha, PEI 4. Diversas cores em estoque. ABNT NBR 15463.", tags:["porcelanato","piso","60x60","1ª linha"], tipo:"fabrica" },
  { id:"c06", nome:"Impermeabilizante Manta Asfáltica 3mm", fornecedor:"ImperPro Brasil", categoria:"Materiais de Construção", categoriaSlug:"materiais-construcao", cidade:"São Paulo", estado:"SP", precoMin:25.00, precoMax:42.00, unidade:"m²", pedidoMinimo:100, prazoEntrega:6, descricao:"Manta asfáltica elastomérica SBS 3mm com tela de poliéster. Para lajes e calhas.", tags:["manta","asfáltica","impermeabilizante","laje"], tipo:"atacado" },
  { id:"c07", nome:"Tubo PVC soldável 100mm 6m branco", fornecedor:"TuboPVC Ind.", categoria:"Materiais de Construção", categoriaSlug:"materiais-construcao", cidade:"Joinville", estado:"SC", precoMin:48.00, precoMax:72.00, unidade:"barra", pedidoMinimo:50, prazoEntrega:5, descricao:"Tubo PVC branco 100mm x 6m, ABNT NBR 5688. Ideal para esgoto e ventilação.", tags:["PVC","tubo","esgoto","100mm"], tipo:"fabrica" },
  { id:"c08", nome:"Telha metálica trapezoidal galvanizada 0,5mm", fornecedor:"MetalTelha Ind.", categoria:"Materiais de Construção", categoriaSlug:"materiais-construcao", cidade:"Contagem", estado:"MG", precoMin:38.00, precoMax:58.00, unidade:"m²", pedidoMinimo:200, prazoEntrega:12, descricao:"Telha metálica trapezoidal galvanizada 0,5mm. Galvanização Z275, corte no comprimento.", tags:["telha","metálica","galvanizada","galpão"], tipo:"fabrica" },
  { id:"c09", nome:"Areia média lavada m³ traço concreto", fornecedor:"Pedreira São João", categoria:"Materiais de Construção", categoriaSlug:"materiais-construcao", cidade:"Mogi das Cruzes", estado:"SP", precoMin:95.00, precoMax:140.00, unidade:"m³", pedidoMinimo:5, prazoEntrega:2, descricao:"Areia média lavada para traço de concreto e argamassa. Entrega com caminhão basculante.", tags:["areia","lavada","concreto","agregado"], tipo:"atacado" },
  { id:"c10", nome:"Porta de madeira maciça 80x210cm", fornecedor:"Madeirex Carpintaria", categoria:"Materiais de Construção", categoriaSlug:"materiais-construcao", cidade:"Linhares", estado:"ES", precoMin:320.00, precoMax:650.00, unidade:"unid", pedidoMinimo:5, prazoEntrega:20, descricao:"Porta de cedro maciço 80x210cm, espessura 35mm. Pré-usinada para dobradiças e maçaneta.", tags:["porta","madeira","maciça","cedro"], tipo:"fabrica" },
  { id:"c11", nome:"Rejunte flexível 1kg várias cores", fornecedor:"ArguMix Ind.", categoria:"Materiais de Construção", categoriaSlug:"materiais-construcao", cidade:"São Paulo", estado:"SP", precoMin:12.00, precoMax:22.00, unidade:"kg", pedidoMinimo:200, prazoEntrega:3, descricao:"Rejunte flexível para juntas de 2 a 12mm. 20 cores disponíveis. ABNT NBR 14992.", tags:["rejunte","flexível","cerâmica","porcelanato"], tipo:"atacado" },
  { id:"c12", nome:"Parafuso sextavado zincado M10x50", fornecedor:"Fixação Total Ferrag.", categoria:"Materiais de Construção", categoriaSlug:"materiais-construcao", cidade:"São Paulo", estado:"SP", precoMin:0.35, precoMax:0.90, unidade:"unid", pedidoMinimo:1000, prazoEntrega:2, descricao:"Parafuso sextavado DIN 933 zincado M10x50. Caixa com 100 unidades. Resistência grau 8.8.", tags:["parafuso","zincado","fixação","M10"], tipo:"atacado" },
  { id:"c13", nome:"Fio elétrico 2,5mm rolo 100m THHN", fornecedor:"CabloFlex Fios", categoria:"Materiais de Construção", categoriaSlug:"materiais-construcao", cidade:"Manaus", estado:"AM", precoMin:145.00, precoMax:210.00, unidade:"rolo", pedidoMinimo:20, prazoEntrega:10, descricao:"Fio THHN 2,5mm antichama rolo 100m, 750V. ABNT NBR NM 247-3. Origem Nexans/Prysmian.", tags:["fio","elétrico","THHN","2,5mm"], tipo:"atacado" },

  // ── Têxtil e Confecção (10) ──────────────────────────────────────────────
  { id:"t01", nome:"Tecido Oxford 100% poliéster 1,50m", fornecedor:"TecidoMax Têxtil", categoria:"Têxtil e Confecção", categoriaSlug:"textil-confeccao", cidade:"Americana", estado:"SP", precoMin:8.50, precoMax:16.00, unidade:"metro", pedidoMinimo:100, prazoEntrega:5, descricao:"Oxford 100% poliéster, 1,50m de largura. 120g/m², resistente. 40 cores em estoque.", tags:["oxford","poliéster","tecido","camiseta"], tipo:"fabrica" },
  { id:"t02", nome:"Malha Piquet PV 65/35 fio 30/1", fornecedor:"MalhaTec Brasil", categoria:"Têxtil e Confecção", categoriaSlug:"textil-confeccao", cidade:"Blumenau", estado:"SC", precoMin:12.00, precoMax:22.00, unidade:"kg", pedidoMinimo:50, prazoEntrega:7, descricao:"Malha Piquet PV 65/35 fio 30/1, 180g/m². Ideal para pólo e uniformes. 30 cores.", tags:["malha","piquet","uniforme","pólo"], tipo:"fabrica" },
  { id:"t03", nome:"Botão de camisa 4 furos 11mm transparente", fornecedor:"BotõesBr", categoria:"Têxtil e Confecção", categoriaSlug:"textil-confeccao", cidade:"São Paulo", estado:"SP", precoMin:0.04, precoMax:0.12, unidade:"unid", pedidoMinimo:5000, prazoEntrega:3, descricao:"Botão de poliéster 4 furos 11mm, transparente. Lavável e durável. Caixa com 144 gross.", tags:["botão","camisa","poliéster","confecção"], tipo:"atacado" },
  { id:"t04", nome:"Zíper de nylon nº 5 metro contínuo", fornecedor:"ZiperPro Brasil", categoria:"Têxtil e Confecção", categoriaSlug:"textil-confeccao", cidade:"Americana", estado:"SP", precoMin:2.80, precoMax:6.00, unidade:"metro", pedidoMinimo:500, prazoEntrega:4, descricao:"Zíper nylon nº 5 contínuo 10 cores, cursor separado. Para malas, roupas esportivas e bolsas.", tags:["zíper","nylon","nº5","confecção"], tipo:"fabrica" },
  { id:"t05", nome:"Jeans Blue Denim 12oz 1,60m", fornecedor:"DenimBrasil Têxtil", categoria:"Têxtil e Confecção", categoriaSlug:"textil-confeccao", cidade:"Americana", estado:"SP", precoMin:22.00, precoMax:38.00, unidade:"metro", pedidoMinimo:50, prazoEntrega:8, descricao:"Jeans Blue Denim 12oz largura 1,60m, 98% algodão/2% elastano. Certificado OEKO-TEX.", tags:["jeans","denim","algodão","calça"], tipo:"fabrica" },
  { id:"t06", nome:"Linha de costura 100% poliéster 120m", fornecedor:"LinhaFina Ind.", categoria:"Têxtil e Confecção", categoriaSlug:"textil-confeccao", cidade:"Rio de Janeiro", estado:"RJ", precoMin:1.20, precoMax:3.00, unidade:"cone", pedidoMinimo:200, prazoEntrega:3, descricao:"Cone de linha 100% poliéster 120/2 120m. 50 cores disponíveis. Alta resistência ao rasgo.", tags:["linha","costura","poliéster","cone"], tipo:"atacado" },
  { id:"t07", nome:"Entretela termocolante 50g/m²", fornecedor:"EntretelaBr", categoria:"Têxtil e Confecção", categoriaSlug:"textil-confeccao", cidade:"Americana", estado:"SP", precoMin:4.50, precoMax:8.00, unidade:"metro", pedidoMinimo:100, prazoEntrega:4, descricao:"Entretela termocolante não tecida 50g/m², largura 90cm. Ideal para golas e punhos.", tags:["entretela","termocolante","confecção","roupa"], tipo:"atacado" },
  { id:"t08", nome:"Agulha industrial DP x 5 (pacote 100)", fornecedor:"NeedlePro Ind.", categoria:"Têxtil e Confecção", categoriaSlug:"textil-confeccao", cidade:"São Paulo", estado:"SP", precoMin:18.00, precoMax:35.00, unidade:"pacote", pedidoMinimo:50, prazoEntrega:3, descricao:"Agulha industrial DP x 5 para overloque nº 10/12/14. Pacote com 100 unidades Schmetz.", tags:["agulha","industrial","overloque","costura"], tipo:"atacado" },
  { id:"t09", nome:"Seda pura jacquard 1,40m", fornecedor:"SedaFina Têxtil", categoria:"Têxtil e Confecção", categoriaSlug:"textil-confeccao", cidade:"São Paulo", estado:"SP", precoMin:85.00, precoMax:150.00, unidade:"metro", pedidoMinimo:20, prazoEntrega:15, descricao:"Seda pura jacquard 1,40m importada China, 22 momme. Para moda premium e alta costura.", tags:["seda","jacquard","importada","alta costura"], tipo:"importacao" },
  { id:"t10", nome:"Elástico chato 3cm branco 50m", fornecedor:"ElásticoTop", categoria:"Têxtil e Confecção", categoriaSlug:"textil-confeccao", cidade:"Sorocaba", estado:"SP", precoMin:45.00, precoMax:80.00, unidade:"rolo", pedidoMinimo:20, prazoEntrega:3, descricao:"Elástico chato 3cm branco rolo 50m. Resistente à lavagem. Para calças, saias e roupas íntimas.", tags:["elástico","chato","confecção","branco"], tipo:"fabrica" },

  // ── Autopeças (10) ───────────────────────────────────────────────────────
  { id:"ap01", nome:"Filtro de óleo Mahle W719/7 universal", fornecedor:"AutoPeças Delta", categoria:"Autopeças", categoriaSlug:"autopecas", cidade:"São Paulo", estado:"SP", precoMin:18.00, precoMax:35.00, unidade:"unid", pedidoMinimo:50, prazoEntrega:2, descricao:"Filtro de óleo Mahle W719/7. Compatível com VW, GM, Ford. Caixa com 25 peças.", tags:["filtro","óleo","Mahle","universal"], tipo:"atacado" },
  { id:"ap02", nome:"Pastilha de freio dianteira Bosch BP806", fornecedor:"Freios & Cia Dist.", categoria:"Autopeças", categoriaSlug:"autopecas", cidade:"Mogi das Cruzes", estado:"SP", precoMin:45.00, precoMax:85.00, unidade:"jogo", pedidoMinimo:20, prazoEntrega:3, descricao:"Pastilha de freio Bosch BP806 dianteira. Compatible Corolla 2015-2023, Civic 2016+.", tags:["pastilha","freio","Bosch","dianteira"], tipo:"atacado" },
  { id:"ap03", nome:"Amortecedor Monroe traseiro Prisma/Onix", fornecedor:"Suspensão Total", categoria:"Autopeças", categoriaSlug:"autopecas", cidade:"São Paulo", estado:"SP", precoMin:120.00, precoMax:210.00, unidade:"par", pedidoMinimo:10, prazoEntrega:3, descricao:"Amortecedor Monroe Reflex traseiro par Prisma/Onix 2012+. Original Monroe com garantia.", tags:["amortecedor","Monroe","Prisma","Onix"], tipo:"atacado" },
  { id:"ap04", nome:"Correia dentada Gates Corolla 2.0", fornecedor:"Transmissão Fortes", categoria:"Autopeças", categoriaSlug:"autopecas", cidade:"Curitiba", estado:"PR", precoMin:65.00, precoMax:120.00, unidade:"unid", pedidoMinimo:20, prazoEntrega:4, descricao:"Correia dentada Gates Corolla 2.0 2015-2022. Kit com tensor e correia. Garantia 30.000km.", tags:["correia","dentada","Gates","Corolla"], tipo:"atacado" },
  { id:"ap05", nome:"Bateria Moura 60Ah M60ED selada", fornecedor:"Auto Center Bateria", categoria:"Autopeças", categoriaSlug:"autopecas", cidade:"Osasco", estado:"SP", precoMin:280.00, precoMax:380.00, unidade:"unid", pedidoMinimo:5, prazoEntrega:1, descricao:"Bateria Moura 60Ah M60ED selada livre de manutenção. Garantia 18 meses. Com carga.", tags:["bateria","Moura","60Ah","selada"], tipo:"atacado" },
  { id:"ap06", nome:"Vela iridium NGK ILFR6B (jogo 4)", fornecedor:"Ignição Premium", categoria:"Autopeças", categoriaSlug:"autopecas", cidade:"São Paulo", estado:"SP", precoMin:120.00, precoMax:200.00, unidade:"jogo", pedidoMinimo:20, prazoEntrega:2, descricao:"Vela de ignição NGK Iridium ILFR6B jogo 4. Compatible Civic/Fit 1.5T Honda. 100.000km.", tags:["vela","iridium","NGK","ignição"], tipo:"atacado" },
  { id:"ap07", nome:"Óleo motor sintético 5W30 1L SN", fornecedor:"LubMax Distribuidora", categoria:"Autopeças", categoriaSlug:"autopecas", cidade:"São Paulo", estado:"SP", precoMin:28.00, precoMax:48.00, unidade:"unid", pedidoMinimo:24, prazoEntrega:2, descricao:"Óleo 5W30 sintético grau SN API, caixa com 12x1L. Valvoline/Castrol/Mobil disponíveis.", tags:["óleo","sintético","5W30","motor"], tipo:"atacado" },
  { id:"ap08", nome:"Farol LED H4 55W 6000K par bivolt", fornecedor:"LightAuto Brasil", categoria:"Autopeças", categoriaSlug:"autopecas", cidade:"São Paulo", estado:"SP", precoMin:85.00, precoMax:160.00, unidade:"par", pedidoMinimo:20, prazoEntrega:5, descricao:"Par de lâmpadas LED H4 55W 6000K, bivolt, plug and play. 10.000 horas de vida útil.", tags:["LED","H4","farol","lâmpada"], tipo:"importacao" },
  { id:"ap09", nome:"Pneu Pirelli Cinturato P1 185/65R15", fornecedor:"Pneus & Rodas Dist.", categoria:"Autopeças", categoriaSlug:"autopecas", cidade:"São Paulo", estado:"SP", precoMin:280.00, precoMax:420.00, unidade:"unid", pedidoMinimo:4, prazoEntrega:3, descricao:"Pneu Pirelli Cinturato P1 185/65R15 88T. Ideal Gol, Uno, Palio. Fabricação atual.", tags:["pneu","Pirelli","Cinturato","185/65R15"], tipo:"atacado" },
  { id:"ap10", nome:"Cabo de vela NGK Fiesta 1.0/1.6 jogo", fornecedor:"ElétricAuto", categoria:"Autopeças", categoriaSlug:"autopecas", cidade:"Guarulhos", estado:"SP", precoMin:55.00, precoMax:95.00, unidade:"jogo", pedidoMinimo:20, prazoEntrega:3, descricao:"Jogo de cabo de vela NGK Fiesta 1.0/1.6 2003-2014. Resistência de 6KΩ/m, anti-RFI.", tags:["cabo","vela","NGK","Fiesta"], tipo:"atacado" },

  // ── Indústria e Manufatura (11) ──────────────────────────────────────────
  { id:"i01", nome:"Resina epóxi bicomponente 1:1 5kg", fornecedor:"QuímicaMax Ind.", categoria:"Indústria e Manufatura", categoriaSlug:"industria-manufatura", cidade:"Cajamar", estado:"SP", precoMin:85.00, precoMax:160.00, unidade:"kit", pedidoMinimo:20, prazoEntrega:5, descricao:"Epóxi bicomponente 5kg (2,5A+2,5B), resistência 60 MPa. Tempo de gel 30min a 25°C.", tags:["epóxi","resina","bicomponente","industrial"], tipo:"fabrica" },
  { id:"i02", nome:"Parafuso allen DIN 912 M8x30 inox A2", fornecedor:"Fixfer Ind.", categoria:"Indústria e Manufatura", categoriaSlug:"industria-manufatura", cidade:"São Paulo", estado:"SP", precoMin:0.45, precoMax:1.20, unidade:"unid", pedidoMinimo:500, prazoEntrega:3, descricao:"Parafuso allen inox A2 M8x30, DIN 912. Resistência à corrosão. Caixa 100un.", tags:["parafuso","allen","inox","DIN912"], tipo:"atacado" },
  { id:"i03", nome:"Rolamento SKF 6205-2RS1 (unid)", fornecedor:"Rolamentos & Cia", categoria:"Indústria e Manufatura", categoriaSlug:"industria-manufatura", cidade:"São Paulo", estado:"SP", precoMin:22.00, precoMax:45.00, unidade:"unid", pedidoMinimo:50, prazoEntrega:3, descricao:"Rolamento rígido de esferas SKF 6205-2RS1. Ø 25x52x15mm, 2 vedações. Para motores elétricos.", tags:["rolamento","SKF","6205","esferas"], tipo:"atacado" },
  { id:"i04", nome:"Correia em V tipo B-50 Gates", fornecedor:"Transmissões Becker", categoria:"Indústria e Manufatura", categoriaSlug:"industria-manufatura", cidade:"Joinville", estado:"SC", precoMin:35.00, precoMax:65.00, unidade:"unid", pedidoMinimo:20, prazoEntrega:4, descricao:"Correia em V Gates HI-POWER tipo B-50. Para ventiladores, compressores e redutores.", tags:["correia","V","Gates","transmissão"], tipo:"atacado" },
  { id:"i05", nome:"Eletrodo revestido 3,25mm E6013 5kg", fornecedor:"SoldaBras Ind.", categoria:"Indústria e Manufatura", categoriaSlug:"industria-manufatura", cidade:"São Caetano do Sul", estado:"SP", precoMin:38.00, precoMax:60.00, unidade:"lata", pedidoMinimo:20, prazoEntrega:3, descricao:"Eletrodo revestido E6013 3,25mm lata 5kg. Cordão suave, escória fácil. AWS A5.1.", tags:["eletrodo","solda","E6013","3,25mm"], tipo:"fabrica" },
  { id:"i06", nome:"Mangueira hidráulica SAE 100R2AT 1/2\"", fornecedor:"HidraFlex Mangueiras", categoria:"Indústria e Manufatura", categoriaSlug:"industria-manufatura", cidade:"Gravataí", estado:"RS", precoMin:18.00, precoMax:32.00, unidade:"metro", pedidoMinimo:50, prazoEntrega:5, descricao:"Mangueira hidráulica 2 tranças SAE 100R2AT 1/2\" WP 400 bar. Corte e prensagem disponíveis.", tags:["mangueira","hidráulica","SAE","400bar"], tipo:"fabrica" },
  { id:"i07", nome:"Graxa lubrificante MP-3 15kg lata", fornecedor:"LubriIndu Ind.", categoria:"Indústria e Manufatura", categoriaSlug:"industria-manufatura", cidade:"São Paulo", estado:"SP", precoMin:85.00, precoMax:140.00, unidade:"lata", pedidoMinimo:10, prazoEntrega:3, descricao:"Graxa multiuso MP-3 15kg base lítio NLGI 3. Para mancais, rolamentos e correntes.", tags:["graxa","lubrificante","MP3","lítio"], tipo:"atacado" },
  { id:"i08", nome:"Inversor de frequência WEG CFW300 1cv", fornecedor:"AutomaBras", categoria:"Indústria e Manufatura", categoriaSlug:"industria-manufatura", cidade:"Jaraguá do Sul", estado:"SC", precoMin:480.00, precoMax:750.00, unidade:"unid", pedidoMinimo:1, prazoEntrega:7, descricao:"Inversor WEG CFW300 0,75kW 220V monofásico. Programação simplificada, proteção IP20.", tags:["inversor","WEG","CFW300","motor"], tipo:"fabrica" },
  { id:"i09", nome:"Cola estrutural acrílica 50ml bisnaga", fornecedor:"AdesivTech", categoria:"Indústria e Manufatura", categoriaSlug:"industria-manufatura", cidade:"São Paulo", estado:"SP", precoMin:12.00, precoMax:25.00, unidade:"unid", pedidoMinimo:100, prazoEntrega:3, descricao:"Cola acrílica bicomponente 10:1 50ml para metais, plásticos e cerâmica. Resistência 250 MPa.", tags:["cola","acrílica","estrutural","adesivo"], tipo:"fabrica" },
  { id:"i10", nome:"Perfil de alumínio T-slot 20x20 1m", fornecedor:"AlumínioPerfil", categoria:"Indústria e Manufatura", categoriaSlug:"industria-manufatura", cidade:"Itajaí", estado:"SC", precoMin:18.00, precoMax:35.00, unidade:"metro", pedidoMinimo:50, prazoEntrega:6, descricao:"Perfil alumínio T-slot 20x20mm série 5 anodizado prata. Para mesas CNC e estruturas.", tags:["alumínio","perfil","T-slot","estrutura"], tipo:"fabrica" },
  { id:"i11", nome:"Disco de corte inox 115x1,0mm (caixa 25)", fornecedor:"AbrasivBras", categoria:"Indústria e Manufatura", categoriaSlug:"industria-manufatura", cidade:"Santo André", estado:"SP", precoMin:4.50, precoMax:8.00, unidade:"unid", pedidoMinimo:25, prazoEntrega:2, descricao:"Disco de corte fino inox 115x1,0x22mm caixa 25 un. Corte preciso sem rebarbas. Tyrolit/Norton.", tags:["disco","corte","inox","115mm"], tipo:"atacado" },

  // ── Tecnologia (8) ───────────────────────────────────────────────────────
  { id:"tech01", nome:"Raspberry Pi 4 Model B 4GB", fornecedor:"TechDist Brasil", categoria:"Tecnologia", categoriaSlug:"tecnologia", cidade:"São Paulo", estado:"SP", precoMin:350.00, precoMax:550.00, unidade:"unid", pedidoMinimo:5, prazoEntrega:7, descricao:"Raspberry Pi 4 4GB RAM. IoT, automação e edge computing. Com NF e garantia.", tags:["Raspberry Pi","IoT","edge","computing"], tipo:"importacao" },
  { id:"tech02", nome:"Switch Cisco SG350-28 PoE 28 portas", fornecedor:"Net Solutions TI", categoria:"Tecnologia", categoriaSlug:"tecnologia", cidade:"Campinas", estado:"SP", precoMin:2800.00, precoMax:4200.00, unidade:"unid", pedidoMinimo:1, prazoEntrega:10, descricao:"Switch gerenciável Cisco SG350-28 PoE, 24 portas 1Gbps + 4 SFP. Garantia 3 anos.", tags:["switch","Cisco","PoE","gerenciável"], tipo:"atacado" },
  { id:"tech03", nome:"Câmera IP PoE 5MP Full Color 24h", fornecedor:"SecureTech CFTV", categoria:"Tecnologia", categoriaSlug:"tecnologia", cidade:"São Paulo", estado:"SP", precoMin:180.00, precoMax:320.00, unidade:"unid", pedidoMinimo:5, prazoEntrega:5, descricao:"Câmera IP 5MP Full Color visão noturna colorida 24h, PoE 802.3af, IP67. H.265+.", tags:["câmera","IP","PoE","CFTV"], tipo:"importacao" },
  { id:"tech04", nome:"Nobreak SMS Sinus Triad 2200VA", fornecedor:"EnergyPro TI", categoria:"Tecnologia", categoriaSlug:"tecnologia", cidade:"São Paulo", estado:"SP", precoMin:1800.00, precoMax:2800.00, unidade:"unid", pedidoMinimo:1, prazoEntrega:5, descricao:"Nobreak senoidal 2200VA/1540W SMS Triad. Autonomia 30min meia carga. 8 tomadas ABNT.", tags:["nobreak","SMS","senoidal","2200VA"], tipo:"atacado" },
  { id:"tech05", nome:"Roteador WiFi 6 Mesh TP-Link Deco XE75", fornecedor:"Conecta Redes", categoria:"Tecnologia", categoriaSlug:"tecnologia", cidade:"Rio de Janeiro", estado:"RJ", precoMin:680.00, precoMax:950.00, unidade:"unid", pedidoMinimo:3, prazoEntrega:5, descricao:"Sistema Mesh WiFi 6E AXE5400 TP-Link Deco XE75. Cobertura até 270m². Tri-band.", tags:["WiFi 6","mesh","TP-Link","roteador"], tipo:"atacado" },
  { id:"tech06", nome:"Servidor Dell PowerEdge T150 Xeon E", fornecedor:"IT Solutions Corp", categoria:"Tecnologia", categoriaSlug:"tecnologia", cidade:"São Paulo", estado:"SP", precoMin:8500.00, precoMax:14000.00, unidade:"unid", pedidoMinimo:1, prazoEntrega:15, descricao:"Servidor Dell PowerEdge T150 Xeon E-2300, 32GB RAM, 2TB SATA. iDRAC Basic.", tags:["servidor","Dell","PowerEdge","Xeon"], tipo:"atacado" },
  { id:"tech07", nome:"Scanner de código de barras 2D Honeywell", fornecedor:"AutoID Brasil", categoria:"Tecnologia", categoriaSlug:"tecnologia", cidade:"São Paulo", estado:"SP", precoMin:280.00, precoMax:450.00, unidade:"unid", pedidoMinimo:5, prazoEntrega:5, descricao:"Leitor 2D Honeywell Voyager XP 1470g USB, leitura QR e DataMatrix. IP52. Garantia 3a.", tags:["scanner","código de barras","2D","Honeywell"], tipo:"atacado" },
  { id:"tech08", nome:"Impressora térmica de etiquetas Zebra ZD220", fornecedor:"PrintSol Sistemas", categoria:"Tecnologia", categoriaSlug:"tecnologia", cidade:"Barueri", estado:"SP", precoMin:950.00, precoMax:1500.00, unidade:"unid", pedidoMinimo:1, prazoEntrega:7, descricao:"Zebra ZD220 impressora térmica direta 203dpi 4pol, USB + série. Para etiquetas e código de barras.", tags:["impressora","Zebra","etiqueta","térmica"], tipo:"atacado" },

  // ── Agronegócio (7) ──────────────────────────────────────────────────────
  { id:"agr01", nome:"Soja em grão certificada IP não-GMO", fornecedor:"Agrotrade Centro-Oeste", categoria:"Agronegócio", categoriaSlug:"agronegocio", cidade:"Sorriso", estado:"MT", precoMin:160.00, precoMax:210.00, unidade:"saca 60kg", pedidoMinimo:100, prazoEntrega:15, descricao:"Soja grão IP não-GMO certificada, colheita atual. Laudo granulometria e umidade.", tags:["soja","grão","IP","não-GMO"], tipo:"fabrica" },
  { id:"agr02", nome:"Fertilizante NPK 04-14-08 50kg", fornecedor:"NutriSolo Agro", categoria:"Agronegócio", categoriaSlug:"agronegocio", cidade:"Rondonópolis", estado:"MT", precoMin:95.00, precoMax:140.00, unidade:"saco", pedidoMinimo:50, prazoEntrega:7, descricao:"NPK formulado 04-14-08 saco 50kg. Plantio de café, cana e soja. Nota de qualidade MAPA.", tags:["fertilizante","NPK","adubo","plantio"], tipo:"fabrica" },
  { id:"agr03", nome:"Milho grão amarelo peneirado 60kg", fornecedor:"Cerealista Campo Verde", categoria:"Agronegócio", categoriaSlug:"agronegocio", cidade:"Campo Verde", estado:"MT", precoMin:55.00, precoMax:78.00, unidade:"saca 60kg", pedidoMinimo:200, prazoEntrega:10, descricao:"Milho amarelo peneirado ≥ Nº 6, umidade ≤14%, aflatoxina ≤20ppb. Saca 60kg.", tags:["milho","grão","ração","animal"], tipo:"fabrica" },
  { id:"agr04", nome:"Defensivo biológico Bacillus subtilis 1L", fornecedor:"BioAgro Solutions", categoria:"Agronegócio", categoriaSlug:"agronegocio", cidade:"Piracicaba", estado:"SP", precoMin:65.00, precoMax:110.00, unidade:"litro", pedidoMinimo:20, prazoEntrega:5, descricao:"Biofungicida Bacillus subtilis QST713 concentrado, para doenças fúngicas em soja e hortaliças.", tags:["biológico","Bacillus","fungicida","orgânico"], tipo:"fabrica" },
  { id:"agr05", nome:"Sementes de girassol ornamental 250g", fornecedor:"SementesBr", categoria:"Agronegócio", categoriaSlug:"agronegocio", cidade:"Holambra", estado:"SP", precoMin:28.00, precoMax:55.00, unidade:"pacote", pedidoMinimo:50, prazoEntrega:4, descricao:"Sementes de girassol ornamental mix cores 250g. Germinação ≥85%, pureza ≥98%.", tags:["sementes","girassol","ornamental","flores"], tipo:"fabrica" },
  { id:"agr06", nome:"Ração para gado nelore 26% PB granel", fornecedor:"RaçãoPet Agro", categoria:"Agronegócio", categoriaSlug:"agronegocio", cidade:"Uberlândia", estado:"MG", precoMin:3.20, precoMax:5.00, unidade:"kg", pedidoMinimo:1000, prazoEntrega:7, descricao:"Ração proteica 26%PB para confinamento nelore. Suplementação mineral e vitamínica inclusa.", tags:["ração","gado","nelore","confinamento"], tipo:"fabrica" },
  { id:"agr07", nome:"Irrigação gotejamento kit 1 hectare", fornecedor:"IrriSol Sistemas", categoria:"Agronegócio", categoriaSlug:"agronegocio", cidade:"Petrolina", estado:"PE", precoMin:2800.00, precoMax:4500.00, unidade:"kit", pedidoMinimo:1, prazoEntrega:15, descricao:"Kit irrigação gotejamento 1ha com gotejadores 1,6L/h, filtros, válvulas e tubulação principal.", tags:["irrigação","gotejamento","1 hectare","kit"], tipo:"fabrica" },

  // ── Limpeza e Higiene (5) ─────────────────────────────────────────────────
  { id:"l01", nome:"Detergente concentrado neutro 5L", fornecedor:"LimpPro Química", categoria:"Limpeza e Higiene", categoriaSlug:"limpeza-higiene", cidade:"São Paulo", estado:"SP", precoMin:18.00, precoMax:32.00, unidade:"galão", pedidoMinimo:50, prazoEntrega:3, descricao:"Detergente neutro concentrado 1:20 galão 5L. Biodegradável, pH 6,5-7. Aprovado ANVISA.", tags:["detergente","neutro","concentrado","biodegradável"], tipo:"fabrica" },
  { id:"l02", nome:"Álcool isopropílico 99,8% 5L", fornecedor:"QuimBras Solventes", categoria:"Limpeza e Higiene", categoriaSlug:"limpeza-higiene", cidade:"Cajamar", estado:"SP", precoMin:55.00, precoMax:90.00, unidade:"galão", pedidoMinimo:20, prazoEntrega:4, descricao:"Álcool isopropílico grau técnico 99,8% 5L. Para limpeza eletrônica e desinfecção industrial.", tags:["álcool","isopropílico","99%","limpeza"], tipo:"fabrica" },
  { id:"l03", nome:"Hipoclorito de sódio 12% 25L", fornecedor:"ClorQuim Ind.", categoria:"Limpeza e Higiene", categoriaSlug:"limpeza-higiene", cidade:"São Paulo", estado:"SP", precoMin:45.00, precoMax:80.00, unidade:"bombona", pedidoMinimo:20, prazoEntrega:3, descricao:"Hipoclorito de sódio 12% ativo 25L. Para desinfecção de água, superfícies e utensílios.", tags:["hipoclorito","cloro","desinfecção","12%"], tipo:"fabrica" },
  { id:"l04", nome:"Sabonete líquido perolado 5L lavanda", fornecedor:"CosmeticLav Ind.", categoria:"Limpeza e Higiene", categoriaSlug:"limpeza-higiene", cidade:"São Paulo", estado:"SP", precoMin:22.00, precoMax:40.00, unidade:"galão", pedidoMinimo:30, prazoEntrega:4, descricao:"Sabonete líquido perolado 5L fragrância lavanda. pH 5,5. Para dispensers de banheiro.", tags:["sabonete","líquido","lavanda","dispenser"], tipo:"fabrica" },
  { id:"l05", nome:"Pano de limpeza microfibra 40x40cm (12un)", fornecedor:"MicroFibra Clean", categoria:"Limpeza e Higiene", categoriaSlug:"limpeza-higiene", cidade:"Americana", estado:"SP", precoMin:32.00, precoMax:55.00, unidade:"pacote", pedidoMinimo:30, prazoEntrega:3, descricao:"Pano microfibra 40x40cm 300g/m² pacote 12un. Absorção 7x o próprio peso. Multicolorido.", tags:["microfibra","pano","limpeza","300g/m²"], tipo:"atacado" },
];
